"""Snapshot selected SiftText nodes and assemble the offline agent prompt.

uv run --no-project python scripts/prepare_agent.py --refresh-browser
uv run --no-project python scripts/prepare_agent.py --check
"""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGENT = ROOT / "agent"
# Read order is intentional: runtime, discovery, tabs, observation, interaction, boundaries.
NODES = (
    "79a4d3dc-c194-4a6c-aac6-1f75a9456147",  # Runtime Invocation
    "7fa0d712-5c99-4ef5-8326-226915ea9aa9",  # Function Discovery
    "11020ca4-868e-4e58-8142-b216053d389d",  # Existing Tab Workflow
    "9b8f7e51-9bf3-47a8-acb7-b62b30759bac",  # Key Functions
    "5f07c543-03d1-4221-b190-de5a8a8c5d66",  # Probing Strategy
    "6baef973-5f05-47e3-aaad-0af8327692e9",  # Accessibility-First Interaction
    "9ee101c4-7df7-4d0d-bbbf-4f1a2cc71c5d",  # Clicking by Visible Text
    "b3dd54e4-b11b-42ea-b9d2-efa678043385",  # Common Pitfalls
    "3d7fd3af-3ebb-4d13-afde-64a91180f1b6",  # Login and Consent
)
PARTS = ("system.md", "browser-runtime.md", "browser-nodes.md")


def render_nodes(rows):
    by_id = {row["id"]: row for row in rows}
    if len(rows) != len(NODES) or set(by_id) != set(NODES):
        raise ValueError("Incomplete or unexpected browser-node export; keeping existing files")
    blocks = ["# Browser reference snapshots\n\nGenerated by scripts/prepare_agent.py via sifttext CLI.\n"
              "These are faithful source snapshots, not an additional workflow. Apply the preceding runtime compatibility rules.\n"]
    for node_id in NODES:
        row = by_id[node_id]
        if not row["updated_at"] or not row["name"]:
            raise ValueError("Missing browser-node provenance")
        blocks.append(f"## {row['name']}\n\nNode: `{node_id}`\nUpdated: `{row['updated_at']}`\n")
        for field in ("scope", "warnings", "ruled_out", "crystallization"):
            if row[field]:
                blocks.append(f"### {field}\n\n{row[field]}\n")
    return "\n".join(blocks)


def build_prompt():
    return "\n\n".join((AGENT / name).read_text().strip() for name in PARTS) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh-browser", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.refresh_browser and args.check:
        parser.error("Refresh and offline check are separate operations")
    if args.refresh_browser:
        ids = ",".join(f"'{node_id}'" for node_id in NODES)
        query = ("SELECT id, name, updated_at, scope, warnings, ruled_out, crystallization "
                 f"FROM nodes WHERE id IN ({ids})")
        response = subprocess.run(["sifttext", "sql", f"query={query}"],
                                  check=True, capture_output=True, text=True, timeout=30)
        (AGENT / "browser-nodes.md").write_text(render_nodes(json.loads(response.stdout)))
    prompt = build_prompt()
    destination = AGENT / "prompt.md"
    if args.check:
        if destination.read_text() != prompt:
            raise SystemExit("agent/prompt.md is stale; run scripts/prepare_agent.py")
    else:
        destination.write_text(prompt)
    print(f"agent/prompt.md: {len(prompt.encode())} bytes, sha256={hashlib.sha256(prompt.encode()).hexdigest()}")


if __name__ == "__main__":
    main()
